export const SQLSERVERCONNECTION = 'SQLSERVERCONNECTION';
export const MYSQLCONNECTION = 'MYSQLCONNECTION';
export const USERREPOSITORY = 'USERDATABASE';
export const TICKETREPOSITORY = 'TICKETREPOSITORY';
